import "dotenv/config"
import { PrismaClient } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log("Seeding database...")

  // ─── CATEGORIES ───
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { name: "Door Hardware/Parts" },
      update: {},
      create: { name: "Door Hardware/Parts", color: "#2563EB", sortOrder: 1 },
    }),
    prisma.category.upsert({
      where: { name: "Metal Raw Materials" },
      update: {},
      create: { name: "Metal Raw Materials", color: "#64748B", sortOrder: 2 },
    }),
    prisma.category.upsert({
      where: { name: "Insulated Metal Panel" },
      update: {},
      create: { name: "Insulated Metal Panel", color: "#0891B2", sortOrder: 3 },
    }),
    prisma.category.upsert({
      where: { name: "Trim & Accessories" },
      update: {},
      create: { name: "Trim & Accessories", color: "#7C3AED", sortOrder: 4 },
    }),
    prisma.category.upsert({
      where: { name: "Foam Insulation" },
      update: {},
      create: { name: "Foam Insulation", color: "#D97706", sortOrder: 5 },
    }),
    prisma.category.upsert({
      where: { name: "Miscellaneous Materials" },
      update: {},
      create: { name: "Miscellaneous Materials", color: "#6B7280", sortOrder: 6 },
    }),
    prisma.category.upsert({
      where: { name: "Doors (by others)" },
      update: {},
      create: { name: "Doors (by others)", color: "#059669", sortOrder: 7 },
    }),
    prisma.category.upsert({
      where: { name: "Fabrication Supplies" },
      update: {},
      create: { name: "Fabrication Supplies", color: "#DC2626", sortOrder: 8 },
    }),
    prisma.category.upsert({
      where: { name: "Caulking & Sealants" },
      update: {},
      create: { name: "Caulking & Sealants", color: "#EA580C", sortOrder: 9 },
    }),
    prisma.category.upsert({
      where: { name: "Plywood & Substrates" },
      update: {},
      create: { name: "Plywood & Substrates", color: "#854D0E", sortOrder: 10 },
    }),
    prisma.category.upsert({
      where: { name: "FRP" },
      update: {},
      create: { name: "FRP", color: "#16A34A", sortOrder: 11 },
    }),
  ])

  const catMap = new Map(categories.map((c) => [c.name, c.id]))
  console.log(`Created ${categories.length} categories`)

  // ─── SUPPLIERS ───
  const suppliers = await Promise.all([
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Adfast" },
    }).catch(() => prisma.supplier.create({ data: { name: "Adfast" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Barbour Plastics" },
    }).catch(() => prisma.supplier.create({ data: { name: "Barbour Plastics" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Bluelinx" },
    }).catch(() => prisma.supplier.create({ data: { name: "Bluelinx" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Chase" },
    }).catch(() => prisma.supplier.create({ data: { name: "Chase" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Dent" },
    }).catch(() => prisma.supplier.create({ data: { name: "Dent" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Dupont" },
    }).catch(() => prisma.supplier.create({ data: { name: "Dupont" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Energy Door Company" },
    }).catch(() => prisma.supplier.create({ data: { name: "Energy Door Company" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Fastener Systems Inc." },
    }).catch(() => prisma.supplier.create({ data: { name: "Fastener Systems Inc." } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Hadco" },
    }).catch(() => prisma.supplier.create({ data: { name: "Hadco" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Industrial Products" },
    }).catch(() => prisma.supplier.create({ data: { name: "Industrial Products" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Insulation Technology" },
    }).catch(() => prisma.supplier.create({ data: { name: "Insulation Technology" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Jamison" },
    }).catch(() => prisma.supplier.create({ data: { name: "Jamison" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Kamco" },
    }).catch(() => prisma.supplier.create({ data: { name: "Kamco" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Kason" },
    }).catch(() => prisma.supplier.create({ data: { name: "Kason" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Lineage" },
    }).catch(() => prisma.supplier.create({ data: { name: "Lineage" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "MetlSpan" },
    }).catch(() => prisma.supplier.create({ data: { name: "MetlSpan" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Millennium Metals" },
    }).catch(() => prisma.supplier.create({ data: { name: "Millennium Metals" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "NEFCO" },
    }).catch(() => prisma.supplier.create({ data: { name: "NEFCO" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Norfab" },
    }).catch(() => prisma.supplier.create({ data: { name: "Norfab" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Pierce Aluminum" },
    }).catch(() => prisma.supplier.create({ data: { name: "Pierce Aluminum" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "PolyCel" },
    }).catch(() => prisma.supplier.create({ data: { name: "PolyCel" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "QXO" },
    }).catch(() => prisma.supplier.create({ data: { name: "QXO" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Refrigeration Hardware Supply Corp" },
    }).catch(() => prisma.supplier.create({ data: { name: "Refrigeration Hardware Supply Corp" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Senneca" },
    }).catch(() => prisma.supplier.create({ data: { name: "Senneca" } })),
    prisma.supplier.upsert({
      where: { id: undefined },
      update: {},
      create: { name: "Tricomp" },
    }).catch(() => prisma.supplier.create({ data: { name: "Tricomp" } })),
  ])

  console.log(`Created ${suppliers.length} suppliers`)

  // ─── ADMIN USER ───
  const admin = await prisma.user.upsert({
    where: { email: "gabe@rsofne.com" },
    update: {},
    create: {
      email: "gabe@rsofne.com",
      name: "Gabe Perez",
      role: "ADMIN",
    },
  })
  console.log("Created admin user")

  // ─── JOBS ───
  await Promise.all([
    prisma.job.upsert({ where: { number: "JOB-2026-001" }, update: {}, create: { name: "ABC Corp Walk-in Cooler", number: "JOB-2026-001" } }),
    prisma.job.upsert({ where: { number: "JOB-2026-002" }, update: {}, create: { name: "Smith Restaurant Freezer", number: "JOB-2026-002" } }),
    prisma.job.upsert({ where: { number: "JOB-2026-003" }, update: {}, create: { name: "Harbor Hotel Cold Storage", number: "JOB-2026-003" } }),
    prisma.job.upsert({ where: { number: "JOB-2026-004" }, update: {}, create: { name: "Metro Market Cooler Expansion", number: "JOB-2026-004" } }),
    prisma.job.upsert({ where: { number: "JOB-2026-005" }, update: {}, create: { name: "Coastal Seafood Processing", number: "JOB-2026-005" } }),
  ])
  console.log("Created 5 jobs")

  // ─── PRODUCTS ───
  const products = [
    { name: "ALUM ANGLE 1.5 x 1.5 x 16\' (.125)", sku: "AET515154", category: "Metal Raw Materials", qty: 7.0, cost: 65.5, unit: "ea", reorder: 2, notes: "CAT: AAN, VAR: AAN-1" },
    { name: "ALUM ANGLE 1.5 x 1.5 x 20\' (.375)", sku: "AET515160", category: "Metal Raw Materials", qty: 0, cost: 90.0, unit: "ea", reorder: 0, notes: "CAT: AAN, VAR: AAN-2" },
    { name: "ALUM ANGLE 2 x 2 x 16\' (.125)", sku: "AET520204", category: "Metal Raw Materials", qty: 41.0, cost: 72.65, unit: "ea", reorder: 8, notes: "CAT: AAN, VAR: AAN-3" },
    { name: "ALUM ANGLE 3 x 5 x 25\' (.375)", sku: "AUT630506", category: "Metal Raw Materials", qty: 0, cost: 559.0, unit: "ea", reorder: 0, notes: "CAT: AAN, VAR: AAN-4" },
    { name: "ALUM ANGLE 3 x 3 x 10\' (.125)", sku: "AET530302", category: "Metal Raw Materials", qty: 0, cost: 60.0, unit: "ea", reorder: 0, notes: "CAT: AAN, VAR: AAN-5" },
    { name: "ADBOND 5635", sku: "5635G", category: "Door Hardware/Parts", qty: 5.0, cost: 275.0, unit: "ea", reorder: 2, notes: "CAT: ADH, VAR: ADH-1" },
    { name: "ADSOLVE 6040", sku: "6040", category: "Door Hardware/Parts", qty: 1.0, cost: 1700.0, unit: "ea", reorder: 2, notes: "CAT: ADH, VAR: ADH-2" },
    { name: "ALUM FLAT", sku: null, category: "Metal Raw Materials", qty: 0, cost: 6.03, unit: "ft", reorder: 0, notes: "CAT: AFS, VAR: AFS-1" },
    { name: "AZEK BOARD 1\" x 6\" x 18\"", sku: "16AZEK", category: "Miscellaneous Materials", qty: 0, cost: 73.0, unit: "ea", reorder: 0, notes: "CAT: AZEK, VAR: AZEK-1" },
    { name: "ALUM ROD", sku: null, category: "Trim & Accessories", qty: 0, cost: 0.89, unit: "ft", reorder: 0, notes: "CAT: CEIL, VAR: CEIL-1" },
    { name: "Junior Beam Clamp", sku: "217728", category: "Trim & Accessories", qty: 50.0, cost: 2.0, unit: "ea", reorder: 10, notes: "CAT: CEIL, VAR: CEIL-2" },
    { name: "Splice Plate Kit 4\"", sku: "CTSPL164HSKIT", category: "Trim & Accessories", qty: 100.0, cost: 12.0, unit: "box", reorder: 20, notes: "CAT: CEIL, VAR: CEIL-3" },
    { name: "Splice Plate Kit 5\"", sku: "CTSPL165HSKIT", category: "Trim & Accessories", qty: 21.0, cost: 6.0, unit: "ea", reorder: 4, notes: "CAT: CEIL, VAR: CEIL-4" },
    { name: "Threaded Rod 1/2-13x10\'", sku: "ATHRCST08C1920ZN", category: "Trim & Accessories", qty: 9.0, cost: 12.0, unit: "ea", reorder: 2, notes: "CAT: CEIL, VAR: CEIL-5" },
    { name: "Threaded Rod 1/2-13x6\'", sku: "ATHRCST08C1152ZN", category: "Trim & Accessories", qty: 0, cost: 7.0, unit: "ea", reorder: 0, notes: "CAT: CEIL, VAR: CEIL-6" },
    { name: "Threaded Rod 3/8-16x10\'", sku: "ATHRCST06C1920ZN", category: "Trim & Accessories", qty: 40.0, cost: 9.0, unit: "ea", reorder: 8, notes: "CAT: CEIL, VAR: CEIL-7" },
    { name: "Threaded Rod 3/8-16x6\'", sku: "ATHRCST06C1152ZN", category: "Trim & Accessories", qty: 30.0, cost: 5.0, unit: "ea", reorder: 6, notes: "CAT: CEIL, VAR: CEIL-8" },
    { name: "Unistrut", sku: "12481", category: "Trim & Accessories", qty: 230.0, cost: 2.94, unit: "ft", reorder: 46, notes: "CAT: CEIL, VAR: CEIL-9" },
    { name: "ALUM COVE BASE", sku: null, category: "Metal Raw Materials", qty: 218.0, cost: 31.86, unit: "ea", reorder: 44, notes: "CAT: COV, VAR: COV-1" },
    { name: "DP.063 4x10", sku: "P03.063H22DT-120-48", category: "Metal Raw Materials", qty: 9.0, cost: 152.39, unit: "ea", reorder: 2, notes: "CAT: DIA, VAR: DIA-1" },
    { name: "DP.063 4x12", sku: "P03.063H22DT-144-48", category: "Metal Raw Materials", qty: 0, cost: 162.76, unit: "ea", reorder: 0, notes: "CAT: DIA, VAR: DIA-2" },
    { name: "DP.063 4x8", sku: "P03.063H22DT-96-48", category: "Metal Raw Materials", qty: 14.0, cost: 133.67, unit: "ea", reorder: 3, notes: "CAT: DIA, VAR: DIA-3" },
    { name: "DP.125 4X10", sku: "P03.125H22DT-120-48", category: "Metal Raw Materials", qty: 8.0, cost: 308.0, unit: "ea", reorder: 2, notes: "CAT: DIA, VAR: DIA-4" },
    { name: "DP.125 4x12", sku: "P03.125H22DT-144-48", category: "Metal Raw Materials", qty: 0, cost: 462.25, unit: "ea", reorder: 0, notes: "CAT: DIA, VAR: DIA-5" },
    { name: "DP.125 4x8", sku: "P03.125H22DT-96-48", category: "Metal Raw Materials", qty: 7.0, cost: 242.0, unit: "ea", reorder: 2, notes: "CAT: DIA, VAR: DIA-6" },
    { name: "DP.25  4 x 8", sku: "P03.25H22DT-96-48", category: "Metal Raw Materials", qty: 3.0, cost: 533.25, unit: "ea", reorder: 2, notes: "CAT: DIA, VAR: DIA-7" },
    { name: "DP.25  4x10", sku: "P03.25H22DT-120-48", category: "Metal Raw Materials", qty: 0, cost: 564.0, unit: "ea", reorder: 0, notes: "CAT: DIA, VAR: DIA-8" },
    { name: "DP.25  4x12", sku: "P03.25H22DT-144-48", category: "Metal Raw Materials", qty: 0, cost: 712.0, unit: "ea", reorder: 0, notes: "CAT: DIA, VAR: DIA-9" },
    { name: "DOW BOARD 4x8", sku: null, category: "Foam Insulation", qty: 20.0, cost: 82.0, unit: "ea", reorder: 4, notes: "CAT: DOW, VAR: DOW-1" },
    { name: "D276 Closer", sku: null, category: "Door Hardware/Parts", qty: 20.0, cost: 49.79, unit: "ea", reorder: 4, notes: "CAT: DRC, VAR: DRC-1" },
    { name: "K1094 CLOSER", sku: "11094000013", category: "Door Hardware/Parts", qty: 31.0, cost: 63.5, unit: "ea", reorder: 6, notes: "CAT: DRC, VAR: DRC-2" },
    { name: "K1094 CLOSER HOOK", sku: "11094000027", category: "Door Hardware/Parts", qty: 50.0, cost: 16.0, unit: "ea", reorder: 10, notes: "CAT: DRC, VAR: DRC-3" },
    { name: "K1097 CLOSER", sku: "11097000008", category: "Door Hardware/Parts", qty: 0, cost: 370.49, unit: "ea", reorder: 0, notes: "CAT: DRC, VAR: DRC-4" },
    { name: "D690 HINGE", sku: null, category: "Door Hardware/Parts", qty: 33.0, cost: 37.45, unit: "ea", reorder: 7, notes: "CAT: DRH, VAR: DRH-1" },
    { name: "K1073 HINGE", sku: "11073000004", category: "Door Hardware/Parts", qty: 0, cost: 302.31, unit: "ea", reorder: 0, notes: "CAT: DRH, VAR: DRH-2" },
    { name: "K1075 HINGE", sku: "11075000004", category: "Door Hardware/Parts", qty: 0, cost: 129.13, unit: "ea", reorder: 0, notes: "CAT: DRH, VAR: DRH-3" },
    { name: "K1240 Hinge", sku: "11240000020", category: "Door Hardware/Parts", qty: 0, cost: 346.0, unit: "ea", reorder: 0, notes: "CAT: DRH, VAR: DRH-4" },
    { name: "K1245 1-1/4OS HINGE", sku: "11245000044", category: "Door Hardware/Parts", qty: 46.0, cost: 37.5, unit: "ea", reorder: 9, notes: "CAT: DRH, VAR: DRH-5" },
    { name: "K1245 1-3/8OS HINGE", sku: "11245000048", category: "Door Hardware/Parts", qty: 17.0, cost: 37.11, unit: "ea", reorder: 3, notes: "CAT: DRH, VAR: DRH-6" },
    { name: "K1245 FL HINGE", sku: "11245000028", category: "Door Hardware/Parts", qty: 0, cost: 27.0, unit: "ea", reorder: 0, notes: "CAT: DRH, VAR: DRH-7" },
    { name: "K1248 1-1/4OS HINGE", sku: "11248000020", category: "Door Hardware/Parts", qty: 108.0, cost: 70.2, unit: "ea", reorder: 22, notes: "CAT: DRH, VAR: DRH-8" },
    { name: "K1248 1-3/8OS HINGE", sku: "11248000024", category: "Door Hardware/Parts", qty: 6.0, cost: 80.0, unit: "ea", reorder: 2, notes: "CAT: DRH, VAR: DRH-9" },
    { name: "K1277 STRAP HINGE", sku: "11277000012", category: "Door Hardware/Parts", qty: 89.0, cost: 59.0, unit: "ea", reorder: 18, notes: "CAT: DRH, VAR: DRH-10" },
    { name: "D90 HANDLE", sku: null, category: "Door Hardware/Parts", qty: 9.0, cost: 62.7, unit: "ea", reorder: 2, notes: "CAT: DRL, VAR: DRL-1" },
    { name: "D90 HANDLE w/ LOCK", sku: null, category: "Door Hardware/Parts", qty: 26.0, cost: 56.25, unit: "ea", reorder: 5, notes: "CAT: DRL, VAR: DRL-2" },
    { name: "K1236", sku: "11236C00006", category: "Door Hardware/Parts", qty: 0, cost: 92.73, unit: "ea", reorder: 0, notes: "CAT: DRL, VAR: DRL-3" },
    { name: "K55 COMP", sku: "10055000068", category: "Door Hardware/Parts", qty: 21.0, cost: 230.0, unit: "ea", reorder: 4, notes: "CAT: DRL, VAR: DRL-4" },
    { name: "K56 LATCH", sku: "10056L05020", category: "Door Hardware/Parts", qty: 48.0, cost: 71.72, unit: "ea", reorder: 10, notes: "CAT: DRL, VAR: DRL-5" },
    { name: "K56 LATCH L", sku: "10056CL05020", category: "Door Hardware/Parts", qty: 12.0, cost: 86.8, unit: "ea", reorder: 2, notes: "CAT: DRL, VAR: DRL-6" },
    { name: "K58 LATCH", sku: "10058L05021", category: "Door Hardware/Parts", qty: 1.0, cost: 81.38, unit: "ea", reorder: 2, notes: "CAT: DRL, VAR: DRL-7" },
    { name: "K78 LATCH", sku: "10078L05020", category: "Door Hardware/Parts", qty: 3.0, cost: 79.0, unit: "ea", reorder: 2, notes: "CAT: DRL, VAR: DRL-8" },
    { name: "K78S SAFEGUARD LATCH", sku: "10078CL5020", category: "Door Hardware/Parts", qty: 0, cost: 107.37, unit: "ea", reorder: 0, notes: "CAT: DRL, VAR: DRL-9" },
    { name: "GLOW PUSH PANEL", sku: "91229000161", category: "Door Hardware/Parts", qty: 289.0, cost: 5.7, unit: "ea", reorder: 58, notes: "CAT: DRM, VAR: DRM-1" },
    { name: "D-800", sku: null, category: "Door Hardware/Parts", qty: 30.0, cost: 4.15, unit: "ea", reorder: 6, notes: "CAT: DRM, VAR: DRM-2" },
    { name: "K481 ISR", sku: "10481A00600", category: "Door Hardware/Parts", qty: 10.0, cost: 11.5, unit: "ea", reorder: 2, notes: "CAT: DRR, VAR: DRR-1" },
    { name: "K486 ISR", sku: "10486D00400", category: "Door Hardware/Parts", qty: 0, cost: 36.5, unit: "ea", reorder: 0, notes: "CAT: DRR, VAR: DRR-2" },
    { name: "K487 ISR", sku: "10487C00400", category: "Door Hardware/Parts", qty: 0, cost: 27.46, unit: "ea", reorder: 0, notes: "CAT: DRR, VAR: DRR-3" },
    { name: "K55 PADD", sku: "10055000028", category: "Door Hardware/Parts", qty: 0, cost: 39.18, unit: "ea", reorder: 0, notes: "CAT: DRR, VAR: DRR-4" },
    { name: "K481 ISR-S", sku: "10481SA0600", category: "Door Hardware/Parts", qty: 6.0, cost: 34.0, unit: "ea", reorder: 2, notes: "CAT: DRR, VAR: DRR-5" },
    { name: "K55 STKR", sku: "10055000020", category: "Door Hardware/Parts", qty: 0, cost: 85.96, unit: "ea", reorder: 0, notes: "CAT: DRS, VAR: DRS-1" },
    { name: "K56 STKR", sku: "10056005003", category: "Door Hardware/Parts", qty: 56.0, cost: 34.0, unit: "ea", reorder: 11, notes: "CAT: DRS, VAR: DRS-2" },
    { name: "K58 STRIKE", sku: "10058005002", category: "Door Hardware/Parts", qty: 0, cost: 27.63, unit: "ea", reorder: 0, notes: "CAT: DRS, VAR: DRS-3" },
    { name: "EPS SHT 2\" x 4\' x 10\'", sku: null, category: "Foam Insulation", qty: 0, cost: 23.0, unit: "ea", reorder: 0, notes: "CAT: EPS, VAR: EPS-1" },
    { name: "EPS SHT 2\" x 4\' x 8\'", sku: null, category: "Foam Insulation", qty: 0, cost: 22.0, unit: "ea", reorder: 0, notes: "CAT: EPS, VAR: EPS-2" },
    { name: "EPS SHT 3.5\" x 4\' x 10\'", sku: null, category: "Foam Insulation", qty: 0, cost: 40.32, unit: "ea", reorder: 0, notes: "CAT: EPS, VAR: EPS-3" },
    { name: "EPS SHT 3.5\" x 4\' x 8\'", sku: null, category: "Foam Insulation", qty: 15.0, cost: 27.22, unit: "ea", reorder: 3, notes: "CAT: EPS, VAR: EPS-4" },
    { name: "EPS SHT 3\" x 4\' x 10\'", sku: null, category: "Foam Insulation", qty: 8.0, cost: 35.0, unit: "ea", reorder: 2, notes: "CAT: EPS, VAR: EPS-5" },
    { name: "EPS SHT 3\" x 4\' x 12\'", sku: null, category: "Foam Insulation", qty: 0, cost: 42.0, unit: "ea", reorder: 0, notes: "CAT: EPS, VAR: EPS-6" },
    { name: "EPS SHT 3\" x 4\' x 8\'", sku: null, category: "Foam Insulation", qty: 0, cost: 31.0, unit: "ea", reorder: 0, notes: "CAT: EPS, VAR: EPS-7" },
    { name: "FRP 4\' X 10\' WHITE", sku: null, category: "Trim & Accessories", qty: 3.0, cost: 70.0, unit: "ea", reorder: 2, notes: "CAT: FRP, VAR: FRP-1" },
    { name: "FRP 4\' X 8\' BLACK", sku: null, category: "Trim & Accessories", qty: 0, cost: 56.0, unit: "ea", reorder: 0, notes: "CAT: FRP, VAR: FRP-2" },
    { name: "FRP 4\' X 8\' WHITE", sku: null, category: "Trim & Accessories", qty: 2.0, cost: 56.0, unit: "ea", reorder: 2, notes: "CAT: FRP, VAR: FRP-3" },
    { name: "FRP 4\' X 10\' BLACK", sku: null, category: "Trim & Accessories", qty: 0, cost: 70.0, unit: "ea", reorder: 0, notes: "CAT: FRP, VAR: FRP-4" },
    { name: "Energy Doors ProE Glass Passthrough Doors", sku: null, category: "Doors (by others)", qty: 0, cost: 2300.0, unit: "ea", reorder: 0, notes: "CAT: GLPTD, VAR: GLPTD-1" },
    { name: "Energy Doors ProE Glass Reach-in Doors", sku: null, category: "Doors (by others)", qty: 0, cost: 1200.0, unit: "ea", reorder: 0, notes: "CAT: GLRID, VAR: GLRID-1" },
    { name: "GALV ANGLE 16GA 2 x 4.25 x 1.5 x 120", sku: null, category: "Metal Raw Materials", qty: 69.0, cost: 27.0, unit: "ea", reorder: 14, notes: "CAT: GLV-A, VAR: GLV-A-1" },
    { name: "GALV ANGLE 16GA 3 x 6 x 10\'", sku: null, category: "Metal Raw Materials", qty: 7.0, cost: 30.0, unit: "ea", reorder: 2, notes: "CAT: GLV-A, VAR: GLV-A-2" },
    { name: "GALV ANGLE 20GA 1.5 x 1.5 x 10\'", sku: null, category: "Metal Raw Materials", qty: 0, cost: 8.83, unit: "ea", reorder: 0, notes: "CAT: GLV-A, VAR: GLV-A-3" },
    { name: "GALV ANGLE 26GA 2 x 4.25 x 2 x 120", sku: null, category: "Metal Raw Materials", qty: 18.0, cost: 26.0, unit: "ea", reorder: 4, notes: "CAT: GLV-A, VAR: GLV-A-4" },
    { name: "GALV ANGLE 26GA 3 x 3 x 10\'", sku: null, category: "Metal Raw Materials", qty: 0, cost: 18.0, unit: "ea", reorder: 0, notes: "CAT: GLV-A, VAR: GLV-A-5" },
    { name: "GALV ANGLE 26GA 3 x 6 x 10\'", sku: null, category: "Metal Raw Materials", qty: 0, cost: 26.0, unit: "ea", reorder: 0, notes: "CAT: GLV-A, VAR: GLV-A-6" },
    { name: "GALV ANGLE 16GA 3 x 3 x 10\'", sku: null, category: "Metal Raw Materials", qty: 0, cost: 26.0, unit: "ea", reorder: 0, notes: "CAT: GLV-A, VAR: GLV-A-7" },
    { name: "Galvanized Steel 26g Gray Embossed", sku: null, category: "Metal Raw Materials", qty: 0, cost: 1.59, unit: "sf", reorder: 0, notes: "CAT: GLV-F, VAR: GLV-F-1" },
    { name: "Galvanized Steel 26g White Embossed", sku: null, category: "Metal Raw Materials", qty: 46428.0, cost: 1.1, unit: "sf", reorder: 9286, notes: "CAT: GLV-F, VAR: GLV-F-2" },
    { name: "Galvanized Steel 26g Smooth White", sku: null, category: "Metal Raw Materials", qty: 9704.0, cost: 1.1, unit: "sf", reorder: 1941, notes: "CAT: GLV-F, VAR: GLV-F-3" },
    { name: "GALVSH 4\'x8\' 16g", sku: "STSGAL.060.48.096", category: "Metal Raw Materials", qty: 3.0, cost: 96.0, unit: "ea", reorder: 2, notes: "CAT: GLV-F, VAR: GLV-F-3" },
    { name: "GALVSH 4\'x8\' 20g", sku: "STSGAL.032.48.096", category: "Metal Raw Materials", qty: 14.0, cost: 80.0, unit: "ea", reorder: 3, notes: "CAT: GLV-F, VAR: GLV-F-4" },
    { name: "GALVSH 4\'x8\' 26g", sku: "STSGAL.018.48.096", category: "Metal Raw Materials", qty: 0, cost: 40.0, unit: "ea", reorder: 0, notes: "CAT: GLV-F, VAR: GLV-F-5" },
    { name: "GALVSH SMOOTH FLATSTOCK", sku: null, category: "Metal Raw Materials", qty: 42.0, cost: 65.0, unit: "ea", reorder: 8, notes: "CAT: GLV-F, VAR: GLV-F-6" },
    { name: "GALVSH EMBOSSED FLATSTOCK", sku: null, category: "Metal Raw Materials", qty: 48.0, cost: 65.0, unit: "ea", reorder: 10, notes: "CAT: GLV-F, VAR: GLV-F-7" },
    { name: "GASKET FOAM", sku: null, category: "Door Hardware/Parts", qty: 500.0, cost: 1.26, unit: "ft", reorder: 100, notes: "CAT: GSK, VAR: GSK-1" },
    { name: "MAGNETIC GASKET 8\'", sku: "SC-625-812", category: "Door Hardware/Parts", qty: 11.5, cost: 25.05, unit: "ea", reorder: 2, notes: "CAT: GSK, VAR: GSK-2" },
    { name: "NEOPRENE GASKET", sku: "74-033", category: "Door Hardware/Parts", qty: 100.0, cost: 2.73, unit: "ft", reorder: 20, notes: "CAT: GSK, VAR: GSK-3" },
    { name: "Wiper Gasket 3\" (No cloth)", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 2.43, unit: "ft", reorder: 0, notes: "CAT: GSK, VAR: GSK-4" },
    { name: "Wiper Gasket 6.5\" (Cloth inserted)", sku: null, category: "Door Hardware/Parts", qty: 500.0, cost: 2.43, unit: "ft", reorder: 100, notes: "CAT: GSK, VAR: GSK-5" },
    { name: "Wiper Gasket 8.5\" (No cloth)", sku: null, category: "Door Hardware/Parts", qty: 600.0, cost: 2.43, unit: "ft", reorder: 120, notes: "CAT: GSK, VAR: GSK-6" },
    { name: "Wiper Gasket 9\" (No cloth)", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 2.5, unit: "ft", reorder: 0, notes: "CAT: GSK, VAR: GSK-7" },
    { name: "Gasket (Misc.)", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 4.13, unit: "ft", reorder: 0, notes: "CAT: GSK, VAR: GSK-8" },
    { name: "HC - 10", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 13.5, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-1" },
    { name: "HC - 12", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 17.76, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-2" },
    { name: "HC - 15", sku: null, category: "Door Hardware/Parts", qty: 9.0, cost: 22.2, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-3" },
    { name: "HC - 18", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 26.64, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-4" },
    { name: "HC - 30", sku: null, category: "Door Hardware/Parts", qty: 5.0, cost: 44.4, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-5" },
    { name: "HC - 31", sku: null, category: "Door Hardware/Parts", qty: 3.0, cost: 45.88, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-6" },
    { name: "HC - 32", sku: null, category: "Door Hardware/Parts", qty: 2.0, cost: 47.36, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-7" },
    { name: "HC - 33", sku: null, category: "Door Hardware/Parts", qty: 3.0, cost: 48.84, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-8" },
    { name: "HC - 34", sku: null, category: "Door Hardware/Parts", qty: 5.0, cost: 50.32, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-9" },
    { name: "HC - 35", sku: null, category: "Door Hardware/Parts", qty: 9.0, cost: 51.8, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-10" },
    { name: "HC - 36", sku: null, category: "Door Hardware/Parts", qty: 5.0, cost: 53.28, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-11" },
    { name: "HC - 37", sku: null, category: "Door Hardware/Parts", qty: 7.0, cost: 54.76, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-12" },
    { name: "HC - 38", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 56.24, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-13" },
    { name: "HC - 39", sku: null, category: "Door Hardware/Parts", qty: 3.0, cost: 57.72, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-14" },
    { name: "HC - 40", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 59.2, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-15" },
    { name: "HC - 41", sku: null, category: "Door Hardware/Parts", qty: 3.0, cost: 60.68, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-16" },
    { name: "HC - 42", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 56.7, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-17" },
    { name: "HC - 43", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 58.05, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-18" },
    { name: "HC - 44", sku: null, category: "Door Hardware/Parts", qty: 3.0, cost: 59.4, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-19" },
    { name: "HC - 45", sku: null, category: "Door Hardware/Parts", qty: 2.0, cost: 60.75, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-20" },
    { name: "HC - 46", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 62.1, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-21" },
    { name: "HC - 47", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 63.45, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-22" },
    { name: "HC - 48", sku: null, category: "Door Hardware/Parts", qty: 4.0, cost: 64.8, unit: "ea", reorder: 2, notes: "CAT: HC, VAR: HC-23" },
    { name: "HC - 52", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 70.2, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-24" },
    { name: "HC - MISC", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 50.0, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-25" },
    { name: "SHC - 19 (228\")", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 18.62, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-26" },
    { name: "SHC - 19.5 (234\")", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 22.6, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-27" },
    { name: "SHC - 32 (384)", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 27.52, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-28" },
    { name: "SHC - 35", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 29.4, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-29" },
    { name: "SHC - 35.6", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 46.8, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-30" },
    { name: "SHC - 37", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 55.6, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-31" },
    { name: "SHC - 37.50", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 42.94, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-32" },
    { name: "SHC - 42", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 54.6, unit: "ea", reorder: 0, notes: "CAT: HC, VAR: HC-33" },
    { name: "Jamison Frigo 2", sku: null, category: "Doors (by others)", qty: 0, cost: 24713.59, unit: "ea", reorder: 0, notes: "CAT: HSRU, VAR: HSRU-1" },
    { name: "Jamison Frigo Replacement Curtain", sku: null, category: "Doors (by others)", qty: 0, cost: 3500.0, unit: "ea", reorder: 0, notes: "CAT: HSRU-P, VAR: HSRU-P-1" },
    { name: "Jamison Frigo Replacement Heater", sku: null, category: "Doors (by others)", qty: 0, cost: 5392.0, unit: "ea", reorder: 0, notes: "CAT: HSRU-P, VAR: HSRU-P-2" },
    { name: "AirGuard 100 Impact Door", sku: null, category: "Doors (by others)", qty: 0, cost: 1800.0, unit: "ea", reorder: 0, notes: "CAT: IPT, VAR: IPT-1" },
    { name: "AirGuard 200 Impact Door", sku: null, category: "Doors (by others)", qty: 0, cost: 2500.0, unit: "ea", reorder: 0, notes: "CAT: IPT, VAR: IPT-2" },
    { name: "AirGuard 100 Impact Door FRAME ONLY", sku: null, category: "Doors (by others)", qty: 0, cost: 1301.0, unit: "ea", reorder: 0, notes: "CAT: IPT, VAR: IPT-3" },
    { name: "AirGuard 200 Impact Door FRAME ONLY", sku: null, category: "Doors (by others)", qty: 0, cost: 1800.0, unit: "ea", reorder: 0, notes: "CAT: IPT, VAR: IPT-4" },
    { name: "Light", sku: "11810LCT400", category: "Trim & Accessories", qty: 0, cost: 94.94, unit: "ea", reorder: 0, notes: "CAT: LGHT, VAR: LGHT-1" },
    { name: "PLYWOOD 1/2", sku: "697055", category: "Miscellaneous Materials", qty: 0, cost: 52.0, unit: "ea", reorder: 0, notes: "CAT: LUMB, VAR: LUMB-1" },
    { name: "PLYWOOD 3/4", sku: "697057", category: "Miscellaneous Materials", qty: 0, cost: 60.0, unit: "ea", reorder: 0, notes: "CAT: LUMB, VAR: LUMB-2" },
    { name: "PLYWOOD 3/8", sku: "697052", category: "Miscellaneous Materials", qty: 0, cost: 50.0, unit: "ea", reorder: 0, notes: "CAT: LUMB, VAR: LUMB-3" },
    { name: "PLYWOOD 5/8", sku: "697056", category: "Miscellaneous Materials", qty: 16.0, cost: 55.0, unit: "ea", reorder: 3, notes: "CAT: LUMB, VAR: LUMB-4" },
    { name: "Metal Door", sku: null, category: "Doors (by others)", qty: 0, cost: 1600.0, unit: "ea", reorder: 0, notes: "CAT: METD, VAR: METD-1" },
    { name: "POLY FILM 10mm", sku: null, category: "Miscellaneous Materials", qty: 10.0, cost: 105.0, unit: "Roll", reorder: 2, notes: "CAT: POLY, VAR: POLY-1" },
    { name: "Battens", sku: "R1020", category: "Trim & Accessories", qty: 1280.0, cost: 1.4, unit: "ft", reorder: 256, notes: "CAT: PVC, VAR: PVC-1" },
    { name: "PVC Corner 10\' Black", sku: null, category: "Trim & Accessories", qty: 16.0, cost: 9.15, unit: "ea", reorder: 3, notes: "CAT: PVC, VAR: PVC-2" },
    { name: "PVC Corner 10\' White", sku: null, category: "Trim & Accessories", qty: 89.0, cost: 1.99, unit: "ft", reorder: 18, notes: "CAT: PVC, VAR: PVC-3" },
    { name: "PVC Corner 8\' Black", sku: null, category: "Trim & Accessories", qty: 0, cost: 9.15, unit: "ea", reorder: 0, notes: "CAT: PVC, VAR: PVC-4" },
    { name: "PVC Corner 8\' Gray", sku: null, category: "Trim & Accessories", qty: 192.0, cost: 1.99, unit: "ft", reorder: 38, notes: "CAT: PVC, VAR: PVC-5" },
    { name: "PVC Corner 8\' White", sku: "601625", category: "Trim & Accessories", qty: 2777.0, cost: 1.99, unit: "ft", reorder: 555, notes: "CAT: PVC, VAR: PVC-6" },
    { name: "ADFOAM 1825/870ML (-25)", sku: "1825", category: "Foam Insulation", qty: 0, cost: 12.95, unit: "ea", reorder: 0, notes: "CAT: SFM, VAR: SFM-1" },
    { name: "ADFOAM 1875/750ML (-5)", sku: "1875-1", category: "Foam Insulation", qty: 78.0, cost: 12.21, unit: "ea", reorder: 16, notes: "CAT: SFM, VAR: SFM-2" },
    { name: "Froth Pak", sku: null, category: "Foam Insulation", qty: 10.0, cost: 385.0, unit: "ea", reorder: 2, notes: "CAT: SFM, VAR: SFM-3" },
    { name: "Kason Slider Lever Assembly", sku: "9850000325", category: "Door Hardware/Parts", qty: 0, cost: 50.0, unit: "ea", reorder: 0, notes: "CAT: SLD-H, VAR: SLD-H-1" },
    { name: "Slider Door Stop", sku: "9860000311", category: "Door Hardware/Parts", qty: 0, cost: 60.0, unit: "ea", reorder: 0, notes: "CAT: SLD-M, VAR: SLD-M-1" },
    { name: "Slider Hardware Kit", sku: "98600000347", category: "Door Hardware/Parts", qty: 0, cost: 230.79, unit: "ea", reorder: 0, notes: "CAT: SLD-M, VAR: SLD-M-2" },
    { name: "Slider Padlock", sku: "18600000023", category: "Door Hardware/Parts", qty: 0, cost: 86.92, unit: "ea", reorder: 0, notes: "CAT: SLD-M, VAR: SLD-M-3" },
    { name: "Slider Strike", sku: "98500000840035K", category: "Door Hardware/Parts", qty: 0, cost: 5.0, unit: "ea", reorder: 0, notes: "CAT: SLD-M, VAR: SLD-M-4" },
    { name: "Slider Tongue", sku: "98500000950035K", category: "Door Hardware/Parts", qty: 0, cost: 13.88, unit: "ea", reorder: 0, notes: "CAT: SLD-M, VAR: SLD-M-5" },
    { name: "Sliding Door Hanger Kit", sku: "9860000860", category: "Door Hardware/Parts", qty: 0, cost: 73.0, unit: "ea", reorder: 0, notes: "CAT: SLD-M, VAR: SLD-M-6" },
    { name: "Kason HD Floor Roller w/ Door Mounted Wedge Plate", sku: "18600000040", category: "Door Hardware/Parts", qty: 0, cost: 46.83, unit: "ea", reorder: 0, notes: "CAT: SLD-R, VAR: SLD-R-1" },
    { name: "Kason Wall Guide (RH)", sku: "18000000018072", category: "Door Hardware/Parts", qty: 0, cost: 532.0, unit: "ea", reorder: 0, notes: "CAT: SLD-R, VAR: SLD-R-2" },
    { name: "SLD 120", sku: "18600000006120", category: "Door Hardware/Parts", qty: 0, cost: 1800.0, unit: "ea", reorder: 0, notes: "CAT: SLD-T, VAR: SLD-T-1" },
    { name: "SLD 144", sku: "18600000006144", category: "Door Hardware/Parts", qty: 0, cost: 2000.0, unit: "ea", reorder: 0, notes: "CAT: SLD-T, VAR: SLD-T-2" },
    { name: "SLD 48", sku: "18600000006048", category: "Door Hardware/Parts", qty: 0, cost: 1000.0, unit: "ea", reorder: 0, notes: "CAT: SLD-T, VAR: SLD-T-3" },
    { name: "SLD 60", sku: "18600000006060", category: "Door Hardware/Parts", qty: 1.0, cost: 1221.98, unit: "ea", reorder: 2, notes: "CAT: SLD-T, VAR: SLD-T-4" },
    { name: "SLD 72", sku: "18600000006072", category: "Door Hardware/Parts", qty: 5.0, cost: 1340.93, unit: "ea", reorder: 2, notes: "CAT: SLD-T, VAR: SLD-T-5" },
    { name: "SLD 96", sku: "18600000006096", category: "Door Hardware/Parts", qty: 3.0, cost: 1616.93, unit: "ea", reorder: 2, notes: "CAT: SLD-T, VAR: SLD-T-6" },
    { name: "Slider A/B Part Replacement Kit", sku: "9800000901", category: "Door Hardware/Parts", qty: 0, cost: 29.99, unit: "ea", reorder: 0, notes: "CAT: SLD-T, VAR: SLD-T-7" },
    { name: "TROLLEY 48\"", sku: "98600003400480R", category: "Door Hardware/Parts", qty: 2.0, cost: 540.0, unit: "ea", reorder: 2, notes: "CAT: SLD-T, VAR: SLD-T-8" },
    { name: "TROLLEY 60\"", sku: "98600003400600R", category: "Door Hardware/Parts", qty: 0, cost: 540.0, unit: "ea", reorder: 0, notes: "CAT: SLD-T, VAR: SLD-T-9" },
    { name: "TROLLEY 72\"", sku: "98600003400720R", category: "Door Hardware/Parts", qty: 1.0, cost: 745.83, unit: "ea", reorder: 2, notes: "CAT: SLD-T, VAR: SLD-T-10" },
    { name: "TROLLEY 96\"", sku: "98600003400960R", category: "Door Hardware/Parts", qty: 2.0, cost: 769.78, unit: "ea", reorder: 2, notes: "CAT: SLD-T, VAR: SLD-T-11" },
    { name: "TROLLEY ROLLER KIT", sku: "9860000341", category: "Door Hardware/Parts", qty: 0, cost: 211.0, unit: "ea", reorder: 0, notes: "CAT: SLD-T, VAR: SLD-T-12" },
    { name: "Jamison 5\' x 7\' Manual Freezer Slider", sku: null, category: "Doors (by others)", qty: 0, cost: 5483.0, unit: "ea", reorder: 0, notes: "CAT: SLD-J, VAR: SLD-J-1" },
    { name: "Jamison 4\' x 7\' Manual Cooler Slider", sku: null, category: "Doors (by others)", qty: 0, cost: 4500.0, unit: "ea", reorder: 0, notes: "CAT: SLD-J, VAR: SLD-J-2" },
    { name: "Butyl Caulk", sku: "CAFSI96PT10WH", category: "Trim & Accessories", qty: 570.0, cost: 4.1, unit: "ea", reorder: 114, notes: "CAT: SLNT, VAR: SLNT-1" },
    { name: "Silicone Sealant (Aluminum)", sku: null, category: "Trim & Accessories", qty: 175.0, cost: 4.0, unit: "ea", reorder: 35, notes: "CAT: SLNT, VAR: SLNT-2" },
    { name: "Silicone Sealant (Clear)", sku: "4801", category: "Trim & Accessories", qty: 91.0, cost: 4.0, unit: "ea", reorder: 18, notes: "CAT: SLNT, VAR: SLNT-3" },
    { name: "Silicone sealant (White)", sku: "4802", category: "Trim & Accessories", qty: 144.5, cost: 4.0, unit: "ea", reorder: 29, notes: "CAT: SLNT, VAR: SLNT-4" },
    { name: "SSSH 0408 11g", sku: null, category: "Metal Raw Materials", qty: 2.0, cost: 475.0, unit: "ea", reorder: 2, notes: "CAT: SSF, VAR: SSF-1" },
    { name: "SSSH 0408 24g Polished", sku: "SSS304.024.48.096.#4", category: "Metal Raw Materials", qty: 0, cost: 183.5, unit: "ea", reorder: 0, notes: "CAT: SSF, VAR: SSF-2" },
    { name: "SSSH 0408 24g Unpolished", sku: null, category: "Metal Raw Materials", qty: 3.0, cost: 183.5, unit: "ea", reorder: 2, notes: "CAT: SSF, VAR: SSF-3" },
    { name: "SSSH 0408 26g", sku: null, category: "Metal Raw Materials", qty: 0, cost: 135.0, unit: "ea", reorder: 0, notes: "CAT: SSF, VAR: SSF-4" },
    { name: "Strip Curtains", sku: null, category: "Doors (by others)", qty: 2.0, cost: 254.0, unit: "ea", reorder: 2, notes: "CAT: STRP, VAR: STRP-1" },
    { name: "T BAR 4\" - 16\'", sku: "CTALUPPBW164HS", category: "Trim & Accessories", qty: 1.0, cost: 200.0, unit: "ea", reorder: 2, notes: "CAT: TBAR, VAR: TBAR-1" },
    { name: "T BAR 5\" - 16", sku: "CTALUPPBW165HS", category: "Trim & Accessories", qty: 24.0, cost: 230.0, unit: "ea", reorder: 5, notes: "CAT: TBAR, VAR: TBAR-2" },
    { name: "Thermometer", sku: "1TM00000001", category: "Trim & Accessories", qty: 33.0, cost: 28.9, unit: "ea", reorder: 7, notes: "CAT: THERM, VAR: THERM-1" },
    { name: "TRAFFIC DOOR 3\' X 7\'", sku: null, category: "Doors (by others)", qty: 0, cost: 1900.0, unit: "ea", reorder: 0, notes: "CAT: TRFCD, VAR: TRFCD-1" },
    { name: "TRAFFIC DOOR 6\' X 7\'", sku: null, category: "Doors (by others)", qty: 0, cost: 3622.0, unit: "ea", reorder: 0, notes: "CAT: TRFCD, VAR: TRFCD-2" },
    { name: "TRAFFIC DOOR FRAME 3\' X 7\'", sku: null, category: "Doors (by others)", qty: 0, cost: 1575.0, unit: "ea", reorder: 0, notes: "CAT: TRFCD, VAR: TRFCD-3" },
    { name: "TRAFFIC DOOR FRAME 6\' X 7\'", sku: null, category: "Doors (by others)", qty: 0, cost: 1800.0, unit: "ea", reorder: 0, notes: "CAT: TRFCD, VAR: TRFCD-4" },
    { name: "URE SHT 3 1/2\"", sku: "118090", category: "Foam Insulation", qty: 5.0, cost: 175.0, unit: "ea", reorder: 2, notes: "CAT: URE, VAR: URE-1" },
    { name: "URE SHT 3\"", sku: "118090", category: "Foam Insulation", qty: 0, cost: 145.0, unit: "ea", reorder: 0, notes: "CAT: URE, VAR: URE-2" },
    { name: "URE SHT 4\"", sku: "118090", category: "Foam Insulation", qty: 0, cost: 170.0, unit: "ea", reorder: 0, notes: "CAT: URE, VAR: URE-3" },
    { name: "VGT Tape 4\"", sku: null, category: "Trim & Accessories", qty: 4.0, cost: 258.0, unit: "Box", reorder: 2, notes: "CAT: VB, VAR: VB-1" },
    { name: "VGT Tape 6\"", sku: null, category: "Trim & Accessories", qty: 4.0, cost: 258.0, unit: "Box", reorder: 2, notes: "CAT: VB, VAR: VB-2" },
    { name: "VGT Tape 9\"", sku: null, category: "Trim & Accessories", qty: 3.0, cost: 258.0, unit: "Box", reorder: 2, notes: "CAT: VB, VAR: VB-3" },
    { name: "VENT PORT - HEATED", sku: "11825LE0004", category: "Trim & Accessories", qty: 8.0, cost: 39.4, unit: "ea", reorder: 2, notes: "CAT: VNTP, VAR: VNTP-1" },
    { name: "VENT PORT - NONHEATED", sku: "11825LE0008", category: "Trim & Accessories", qty: 0, cost: 48.8, unit: "ea", reorder: 0, notes: "CAT: VNTP, VAR: VNTP-2" },
    { name: "WIN H 1414", sku: "55082-4A", category: "Door Hardware/Parts", qty: 4.0, cost: 245.75, unit: "ea", reorder: 2, notes: "CAT: WIN, VAR: WIN-1" },
    { name: "WIN H 1424", sku: "55082-9A", category: "Door Hardware/Parts", qty: 0, cost: 200.0, unit: "ea", reorder: 0, notes: "CAT: WIN, VAR: WIN-2" },
    { name: "WIN NH 1414", sku: "55084-4", category: "Door Hardware/Parts", qty: 3.0, cost: 180.0, unit: "ea", reorder: 2, notes: "CAT: WIN, VAR: WIN-3" },
    { name: "WIN NH 1424", sku: "55084-9", category: "Door Hardware/Parts", qty: 1.0, cost: 150.0, unit: "ea", reorder: 2, notes: "CAT: WIN, VAR: WIN-4" },
    { name: "WIN NH 2446", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 800.0, unit: "ea", reorder: 0, notes: "CAT: WIN, VAR: WIN-5" },
    { name: "WIN NH 7846", sku: null, category: "Door Hardware/Parts", qty: 0, cost: 1020.0, unit: "ea", reorder: 0, notes: "CAT: WIN, VAR: WIN-6" },
    { name: "Misc Foam Insulation", sku: null, category: "Foam Insulation", qty: 0, cost: 0, unit: "ea", reorder: 0, notes: "CAT: INS, VAR: INS-MISC" },
    { name: "EPDM Rubber Roll", sku: null, category: "Trim & Accessories", qty: 1.0, cost: 1084.0, unit: "ea", reorder: 2, notes: "CAT: ROOF, VAR: ROOF" },
    { name: "4x8 Stainless Steel Polished 304 - 24ga", sku: null, category: "Metal Raw Materials", qty: 10.0, cost: 84.19, unit: "ea", reorder: 2, notes: null },
    { name: "K487 Inside Release", sku: "10487C00400", category: "Miscellaneous Materials", qty: 0, cost: 27.46, unit: "ea", reorder: 0, notes: null },
    { name: "Air Switch", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 93.56, unit: "ea", reorder: 0, notes: null },
    { name: "Aluminum Cove Base", sku: null, category: "Metal Raw Materials", qty: 218.0, cost: 31.86, unit: "ea", reorder: 44, notes: null },
    { name: "Battery Wireless D Tabs", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 62.58, unit: "ea", reorder: 0, notes: null },
    { name: "CDX FR PLY 4x8", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 52.84, unit: "ea", reorder: 0, notes: null },
    { name: "Connecting Link", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 2.64, unit: "ea", reorder: 0, notes: null },
    { name: "Dart Mounted Mag Gasket", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 3.3, unit: "ea", reorder: 0, notes: null },
    { name: "Diamond Plate .125 4\' x 10\'", sku: "P03.125H22DT-120-48", category: "Metal Raw Materials", qty: 8.0, cost: 318.0, unit: "ea", reorder: 2, notes: null },
    { name: "Diamond Plate .25 4\' x 12\'", sku: "P03.25H22DT-144-48", category: "Miscellaneous Materials", qty: 0, cost: 712.0, unit: "ea", reorder: 0, notes: null },
    { name: "Encoder, BMP Incremental", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 100.0, unit: "ea", reorder: 0, notes: null },
    { name: "Filter Regulator 8652ACDP3F101G", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 711.24, unit: "ea", reorder: 0, notes: null },
    { name: "Window 14\" x 24\" Non-Heated", sku: "55084-9", category: "Door Hardware/Parts", qty: 1.0, cost: 150.25, unit: "ea", reorder: 2, notes: null },
    { name: "Air Cylinder Control Assembly", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1500.0, unit: "ea", reorder: 0, notes: null },
    { name: "119-052B Unroll Sensor", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 172.66, unit: "ea", reorder: 0, notes: null },
    { name: "488L Inside Release Panic Bar", sku: "10488CR0318600", category: "Miscellaneous Materials", qty: 0, cost: 201.03, unit: "ea", reorder: 0, notes: null },
    { name: "78S SAFEGUARD® HANDLE", sku: "10078S06022", category: "Miscellaneous Materials", qty: 0, cost: 260.0, unit: "ea", reorder: 0, notes: null },
    { name: "ADFOAM 1875", sku: "1875-1", category: "Foam Insulation", qty: 37.2, cost: 12.21, unit: "ea", reorder: 7, notes: null },
    { name: "Air Cylinder, Rear Drip", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 114.32, unit: "ea", reorder: 0, notes: null },
    { name: "Aluminum Angle 2\" x 3\" (.125)", sku: "AUT520304", category: "Miscellaneous Materials", qty: 0, cost: 80.0, unit: "ea", reorder: 0, notes: null },
    { name: "Battery 3.67V, 1650", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 84.56, unit: "ea", reorder: 0, notes: null },
    { name: "Border Window", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 28.75, unit: "ea", reorder: 0, notes: null },
    { name: "Cable for Light Curtains", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 109.75, unit: "ea", reorder: 0, notes: null },
    { name: "CRASH BAR", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 276.08, unit: "ea", reorder: 0, notes: null },
    { name: "Aluminum Embossed .032 4\' x 8\' Sheets", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 43.0, unit: "ea", reorder: 0, notes: null },
    { name: "Assembly Track LH Front", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 598.83, unit: "ea", reorder: 0, notes: null },
    { name: "Kason 1097 Closer", sku: "11097000008", category: "Miscellaneous Materials", qty: 0, cost: 370.49, unit: "ea", reorder: 0, notes: null },
    { name: "Aluminum Smooth .063 x 4\' x 10\' Sheet", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 86.2, unit: "ea", reorder: 0, notes: null },
    { name: "Assembly Track, LH Rear", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 602.91, unit: "ea", reorder: 0, notes: null },
    { name: "DBSC 5GAL", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 155.0, unit: "ea", reorder: 0, notes: null },
    { name: "Diamond Plate .063 4\' x 10\'", sku: "P03.063H22DT-120-48", category: "Metal Raw Materials", qty: 17.0, cost: 175.0, unit: "ea", reorder: 3, notes: null },
    { name: "Drive Link", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 112.07, unit: "ea", reorder: 0, notes: null },
    { name: "Encoder Kit", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 484.88, unit: "ea", reorder: 0, notes: null },
    { name: "EPS Sheet 3.5\" x 4\' x 8\'", sku: null, category: "Foam Insulation", qty: 9.0, cost: 27.22, unit: "ea", reorder: 2, notes: null },
    { name: "FROST STOP 2", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 2.38, unit: "ea", reorder: 0, notes: null },
    { name: "FRP ADHESIVE", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 46.6, unit: "ea", reorder: 0, notes: null },
    { name: "Galvanized Steel Coil - Textured Gray (26ga)", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1.59, unit: "ea", reorder: 0, notes: null },
    { name: "15\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 14.0, cost: 24.0, unit: "ea", reorder: 3, notes: null },
    { name: "33\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 11.0, cost: 52.8, unit: "ea", reorder: 2, notes: null },
    { name: "Aluminum Angle 2\" x 2\" (.125)", sku: "AET520204", category: "Trim & Accessories", qty: 24.0, cost: 72.65, unit: "ea", reorder: 5, notes: null },
    { name: "PVC Batten - White 8\'", sku: "R1020-WHITE", category: "Trim & Accessories", qty: 784.0, cost: 1.53, unit: "ea", reorder: 157, notes: null },
    { name: "BLK PSH BATTEN", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 65.78, unit: "ea", reorder: 0, notes: null },
    { name: "Control Valve Numatics", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 352.94, unit: "ea", reorder: 0, notes: null },
    { name: "DBSC 55GAL DRUM", sku: null, category: "Door Hardware/Parts", qty: 1.0, cost: 875.0, unit: "ea", reorder: 2, notes: null },
    { name: "Dow 60PSI 4\' x 8\' x 2\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 57.04, unit: "ea", reorder: 0, notes: null },
    { name: "Diamond Plate .125 4\' x 12\'", sku: "P03.125H22DT-144-48", category: "Miscellaneous Materials", qty: 0, cost: 359.0, unit: "ea", reorder: 0, notes: null },
    { name: "Drive Chain", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 5.65, unit: "ea", reorder: 0, notes: null },
    { name: "Encoder Cable", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 54.92, unit: "ea", reorder: 0, notes: null },
    { name: "EPS - NONSTAND", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 47.52, unit: "ea", reorder: 0, notes: null },
    { name: "Kason Heavy Duty Floor Roller w/ Strike", sku: "18600000042", category: "Miscellaneous Materials", qty: 0, cost: 80.0, unit: "ea", reorder: 0, notes: null },
    { name: "FRP .090 4\' x 8\' White", sku: "F48", category: "Trim & Accessories", qty: 2.0, cost: 57.6, unit: "ea", reorder: 2, notes: null },
    { name: "HINGE 1073", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 302.31, unit: "ea", reorder: 0, notes: null },
    { name: "Jam Control Cord", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1315.54, unit: "ea", reorder: 0, notes: null },
    { name: "JUNIOR BEAM CLAMP 3/8\"", sku: null, category: "Trim & Accessories", qty: 38.0, cost: 1.2, unit: "ea", reorder: 8, notes: null },
    { name: "Dow 40PSI 4\' x 8\' x 3\"", sku: "12031471", category: "Miscellaneous Materials", qty: 0, cost: 53.0, unit: "ea", reorder: 0, notes: null },
    { name: "Diamond Plate .063 4\' x 12\'", sku: "P03.063H22DT-144-48", category: "Miscellaneous Materials", qty: 0, cost: 189.0, unit: "ea", reorder: 0, notes: null },
    { name: "Diamond Plate .25 4\' x 8\'", sku: "P03.25H22DT-96-48", category: "Metal Raw Materials", qty: 3.0, cost: 533.25, unit: "ea", reorder: 2, notes: null },
    { name: "Drive Sprocket", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 37.24, unit: "ea", reorder: 0, notes: null },
    { name: "EPDM RUBBER ROLL 12\"", sku: null, category: "Miscellaneous Materials", qty: 1.0, cost: 0, unit: "ea", reorder: 2, notes: null },
    { name: "EPS Sheet 3\" x 4\' x 9\'", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 31.11, unit: "ea", reorder: 0, notes: null },
    { name: "EPS SPLINE", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.55, unit: "ea", reorder: 0, notes: null },
    { name: "Fuse, 160mA  500V SIBA", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 13.05, unit: "ea", reorder: 0, notes: null },
    { name: "18\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 4.0, cost: 28.8, unit: "ea", reorder: 2, notes: null },
    { name: "39\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 3.0, cost: 62.4, unit: "ea", reorder: 2, notes: null },
    { name: "K1245 1-1/4 OS Hinge", sku: "11245000044", category: "Door Hardware/Parts", qty: 44.0, cost: 37.5, unit: "ea", reorder: 9, notes: null },
    { name: "HINGE 1377", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 77.41, unit: "ea", reorder: 0, notes: null },
    { name: "Jamison Battery", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 2.0, unit: "ea", reorder: 0, notes: null },
    { name: "K1236 Latch", sku: "11236C00006", category: "Miscellaneous Materials", qty: 0, cost: 92.73, unit: "ea", reorder: 0, notes: null },
    { name: "K56 Latch (Body Chrome)", sku: "10056L05020", category: "Door Hardware/Parts", qty: 45.0, cost: 77.72, unit: "ea", reorder: 9, notes: null },
    { name: "Dow 30PSI 4\' x 8\' x 3\"", sku: "12031445", category: "Foam Insulation", qty: 20.0, cost: 82.0, unit: "ea", reorder: 4, notes: null },
    { name: "Diamond Plate .25 4\' x 10\'", sku: "P03.25H22DT-120-48", category: "Miscellaneous Materials", qty: 0, cost: 564.0, unit: "ea", reorder: 0, notes: null },
    { name: "Encoder", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1260.0, unit: "ea", reorder: 0, notes: null },
    { name: "EPS Sheet 2\" x 4\' x 10\'", sku: null, category: "Foam Insulation", qty: 15.0, cost: 23.04, unit: "ea", reorder: 3, notes: null },
    { name: "EPS SPLINE 4\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.97, unit: "ea", reorder: 0, notes: null },
    { name: "FRP 350", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1.15, unit: "ea", reorder: 0, notes: null },
    { name: "Fuse, 250 mA  500V SIBA", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 14.01, unit: "ea", reorder: 0, notes: null },
    { name: "Gear Reducer", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 763.08, unit: "ea", reorder: 0, notes: null },
    { name: "30\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 5.0, cost: 48.0, unit: "ea", reorder: 2, notes: null },
    { name: "35\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 9.0, cost: 56.0, unit: "ea", reorder: 2, notes: null },
    { name: "Fuse , FNQ-R 15 AMP", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 29.3, unit: "ea", reorder: 0, notes: null },
    { name: "31\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 6.0, cost: 49.6, unit: "ea", reorder: 2, notes: null },
    { name: "36\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 6.0, cost: 57.6, unit: "ea", reorder: 2, notes: null },
    { name: "41\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 3.0, cost: 65.6, unit: "ea", reorder: 2, notes: null },
    { name: "38\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 11.0, cost: 60.8, unit: "ea", reorder: 2, notes: null },
    { name: "43\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 4.0, cost: 68.8, unit: "ea", reorder: 2, notes: null },
    { name: "48\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 4.0, cost: 76.8, unit: "ea", reorder: 2, notes: null },
    { name: "HINGE 1075", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 129.13, unit: "ea", reorder: 0, notes: null },
    { name: "45\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 2.0, cost: 72.0, unit: "ea", reorder: 2, notes: null },
    { name: "Heater Cable - MISC", sku: "64-250", category: "Miscellaneous Materials", qty: 0, cost: 1.6, unit: "ea", reorder: 0, notes: null },
    { name: "HINGE D690", sku: null, category: "Door Hardware/Parts", qty: 11.0, cost: 37.45, unit: "ea", reorder: 2, notes: null },
    { name: "Jamison Stay Roller Assembly", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 114.58, unit: "ea", reorder: 0, notes: null },
    { name: "K55 BODY", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 170.96, unit: "ea", reorder: 0, notes: null },
    { name: "K56 Latch w/ Keyed Lock", sku: "10056CL05020", category: "Door Hardware/Parts", qty: 12.0, cost: 86.8, unit: "ea", reorder: 2, notes: null },
    { name: "Heated Pull Chord Switch", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 299.46, unit: "ea", reorder: 0, notes: null },
    { name: "K1245 Flush Hinge", sku: "11245000028", category: "Miscellaneous Materials", qty: 0, cost: 27.0, unit: "ea", reorder: 0, notes: null },
    { name: "Jamison A/B Part Replacement Kit", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 29.99, unit: "ea", reorder: 0, notes: null },
    { name: "Jam Air Pressure Swtich", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 58.15, unit: "ea", reorder: 0, notes: null },
    { name: "Jam Reverse Edge Battery", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 24.18, unit: "ea", reorder: 0, notes: null },
    { name: "K55 Complete", sku: "10055000068", category: "Door Hardware/Parts", qty: 20.0, cost: 230.0, unit: "ea", reorder: 4, notes: null },
    { name: "Key Square", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1.22, unit: "ea", reorder: 0, notes: null },
    { name: "Kason Slider Recessed Handle", sku: "9850000036", category: "Miscellaneous Materials", qty: 0, cost: 5.77, unit: "ea", reorder: 0, notes: null },
    { name: "LS Drive Sprocket", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 37.24, unit: "ea", reorder: 0, notes: null },
    { name: "Keypad W/ RG LED", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 85.12, unit: "ea", reorder: 0, notes: null },
    { name: "LH Volt Heater", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 2514.75, unit: "ea", reorder: 0, notes: null },
    { name: "Mounting Bracket", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 100.0, unit: "ea", reorder: 0, notes: null },
    { name: "PAD HASP - 36", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 43.39, unit: "ea", reorder: 0, notes: null },
    { name: "Phote Eye PR Rytec", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 28.63, unit: "ea", reorder: 0, notes: null },
    { name: "23/32X48X96 ARAUCO AC RADIATA PINE Sanded (3/4\")", sku: "697057", category: "Miscellaneous Materials", qty: 54.0, cost: 41.51, unit: "ea", reorder: 11, notes: null },
    { name: "PUSH BAR", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 218.58, unit: "ea", reorder: 0, notes: null },
    { name: "Replacement Dynamic Roll", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 3771.94, unit: "ea", reorder: 0, notes: null },
    { name: "Rivnut SST M5X0.9", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.33, unit: "ea", reorder: 0, notes: null },
    { name: "Kason Slider Exterior Pull Handle", sku: "15001SP0004", category: "Miscellaneous Materials", qty: 0, cost: 14.87, unit: "ea", reorder: 0, notes: null },
    { name: "Limit Switch Chain", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 28.67, unit: "ea", reorder: 0, notes: null },
    { name: "Micro Safety Switch", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 30.83, unit: "ea", reorder: 0, notes: null },
    { name: "National Gasket 1.5\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 6.0, unit: "ea", reorder: 0, notes: null },
    { name: "11/32X48X96 ARAUCO AC RADIATA PINE Sanded (3/8\")", sku: "697052", category: "Miscellaneous Materials", qty: 0, cost: 50.0, unit: "ea", reorder: 0, notes: null },
    { name: "Reducer 15-1", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 517.99, unit: "ea", reorder: 0, notes: null },
    { name: "RETAINER", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0, unit: "ea", reorder: 0, notes: null },
    { name: "Self Drilling Screws", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.14, unit: "ea", reorder: 0, notes: null },
    { name: "35\' - HEATER, WIRE FIBERGLASS BRAID, 115V, -10DEG, SINGLE WRAP", sku: "64-200", category: "Door Hardware/Parts", qty: 2.0, cost: 52.5, unit: "ea", reorder: 2, notes: null },
    { name: "Slider Gasket - 6.5\' (Cloth Inserted)", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1.54, unit: "ea", reorder: 0, notes: null },
    { name: "Spider Connector Cable", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 255.3, unit: "ea", reorder: 0, notes: null },
    { name: "SSSH 0408 26", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 126.0, unit: "ea", reorder: 0, notes: null },
    { name: "Slider Tongue - Non-padlock", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 13.88, unit: "ea", reorder: 0, notes: null },
    { name: "Unroll Sensor Bracket", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 2.92, unit: "ea", reorder: 0, notes: null },
    { name: "TRYMER 200L 4\" - 48\" X 96\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 183.6, unit: "ea", reorder: 0, notes: null },
    { name: "Light Curtain Transmitter", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 658.24, unit: "ea", reorder: 0, notes: null },
    { name: "Motor, 1.5KW STD w pin", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 970.21, unit: "ea", reorder: 0, notes: null },
    { name: "Non Heated PULL CORD", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 172.54, unit: "ea", reorder: 0, notes: null },
    { name: "PE Telco 3215", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 56.36, unit: "ea", reorder: 0, notes: null },
    { name: "Pressure Sensor SWTCH", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 26.43, unit: "ea", reorder: 0, notes: null },
    { name: "Replacement Brake", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 295.0, unit: "ea", reorder: 0, notes: null },
    { name: "RH Volt Heater", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 2514.75, unit: "ea", reorder: 0, notes: null },
    { name: "19\' - HEATER, WIRE FIBERGLASS BRAID, 115V, -10DEG, SINGLE WRAP", sku: "64-200", category: "Door Hardware/Parts", qty: 12.0, cost: 28.5, unit: "ea", reorder: 2, notes: null },
    { name: "37.5\' - HEATER, WIRE FIBERGLASS BRAID, 115V, -10DEG, SINGLE WRAP", sku: "64-200", category: "Door Hardware/Parts", qty: 6.0, cost: 42.94, unit: "ea", reorder: 2, notes: null },
    { name: "Motor", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 421.53, unit: "ea", reorder: 0, notes: null },
    { name: "GASKET, 100\' ROLL JAMISON", sku: "74-033", category: "Door Hardware/Parts", qty: 105.26, cost: 2.67, unit: "ea", reorder: 21, notes: null },
    { name: "PE Telco 3000", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 46.04, unit: "ea", reorder: 0, notes: null },
    { name: "National Gasket 1\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 5.5, unit: "ea", reorder: 0, notes: null },
    { name: "Photoe Eye Pair", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 285.0, unit: "ea", reorder: 0, notes: null },
    { name: "PMC24", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 75.0, unit: "ea", reorder: 0, notes: null },
    { name: "Receptacle Spider WIre", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0, unit: "ea", reorder: 0, notes: null },
    { name: "Replacement Gasket", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 71.46, unit: "ea", reorder: 0, notes: null },
    { name: "Screw Button HD Socket", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.46, unit: "ea", reorder: 0, notes: null },
    { name: "POLY FOAM", sku: null, category: "Foam Insulation", qty: 500.0, cost: 1.26, unit: "ea", reorder: 100, notes: null },
    { name: "Replacement Ballast", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 125.0, unit: "ea", reorder: 0, notes: null },
    { name: "Reversing Edge Complete Assembl", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 140.2, unit: "ea", reorder: 0, notes: null },
    { name: "Serrated Nut", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.18, unit: "ea", reorder: 0, notes: null },
    { name: "32\' - HEATER, WIRE FIBERGLASS BRAID, 115V, -10DEG, SINGLE WRAP", sku: "64-200", category: "Door Hardware/Parts", qty: 3.0, cost: 48.0, unit: "ea", reorder: 2, notes: null },
    { name: "SSSH 0408 24 - Polished", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 183.5, unit: "ea", reorder: 0, notes: null },
    { name: "STRIKER", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 20.33, unit: "ea", reorder: 0, notes: null },
    { name: "Threaded Rod 3/8\" x 6\'", sku: "ATHRCST06C1152ZN", category: "Trim & Accessories", qty: 96.0, cost: 2.52, unit: "ea", reorder: 19, notes: null },
    { name: "Slider Door Track System - 60\"", sku: "98600003200610", category: "Miscellaneous Materials", qty: 0, cost: 79.69, unit: "ea", reorder: 0, notes: null },
    { name: "SSSH 0410 24", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 246.44, unit: "ea", reorder: 0, notes: null },
    { name: "Sweep Gasket 3\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 1.35, unit: "ea", reorder: 0, notes: null },
    { name: "TRACK BOLT SST", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.21, unit: "ea", reorder: 0, notes: null },
    { name: "Unroll Sensor PF", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 171.65, unit: "ea", reorder: 0, notes: null },
    { name: "TRYMER 200L 3-1/2\" - 48\" X 96\"", sku: "118090", category: "Foam Insulation", qty: 17.0, cost: 165.0, unit: "ea", reorder: 3, notes: null },
    { name: "Window 14\" x 14\" Heated", sku: "55082-4A", category: "Miscellaneous Materials", qty: 0, cost: 245.75, unit: "ea", reorder: 0, notes: null },
    { name: "Slider Door Track System - 96\"", sku: "98600003201050", category: "Miscellaneous Materials", qty: 0, cost: 117.67, unit: "ea", reorder: 0, notes: null },
    { name: "SPRING SST", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0.33, unit: "ea", reorder: 0, notes: null },
    { name: "SSSH 0410 26", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 86.82, unit: "ea", reorder: 0, notes: null },
    { name: "Switch, Pizzato FR551", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 30.83, unit: "ea", reorder: 0, notes: null },
    { name: "Transformer", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 131.27, unit: "ea", reorder: 0, notes: null },
    { name: "TRYMER 200L 5\" - 48\" X 96\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 223.0, unit: "ea", reorder: 0, notes: null },
    { name: "Window 5\" Throat 14\" x 14\" Heated Glass and Frame", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 156.5, unit: "ea", reorder: 0, notes: null },
    { name: "STEGO WRAP 10MIL", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 0, unit: "ea", reorder: 0, notes: null },
    { name: "Trolley Wheel", sku: "98600SS095", category: "Door Hardware/Parts", qty: 6.0, cost: 35.5, unit: "ea", reorder: 2, notes: null },
    { name: "TRYMER 200L 6\" - 48\" X 96\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 233.5, unit: "ea", reorder: 0, notes: null },
    { name: "TRYMER 200L 3\" - 48\" X 96\"", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 116.0, unit: "ea", reorder: 0, notes: null },
    { name: "Valve Plug Numatics", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 36.1, unit: "ea", reorder: 0, notes: null },
    { name: "Window- 14\" x 23\" Non-Heated", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 350.0, unit: "ea", reorder: 0, notes: null },
    { name: "Window 13\" x 23\" Non-Heated", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 150.0, unit: "ea", reorder: 0, notes: null },
    { name: "Zipper Repair Kit", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 39.66, unit: "ea", reorder: 0, notes: null },
    { name: "Window Loop", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 49.56, unit: "ea", reorder: 0, notes: null },
    { name: "Window 14\" x 14\" Non-Heated", sku: "55084-4", category: "Door Hardware/Parts", qty: 3.0, cost: 180.0, unit: "ea", reorder: 2, notes: null },
    { name: "Window 14\" x 24\" Heated Window", sku: "5082-9A", category: "Miscellaneous Materials", qty: 0, cost: 236.5, unit: "ea", reorder: 0, notes: null },
    { name: "Wire, Motor VFD Signal", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 4.86, unit: "ea", reorder: 0, notes: null },
    { name: "Wiper Gasket 3\"", sku: null, category: "Door Hardware/Parts", qty: 99.82, cost: 1.35, unit: "ea", reorder: 20, notes: null },
    { name: "Unistrut - 1-5/8\" x 1-5/8\" x 10\'", sku: "12481", category: "Trim & Accessories", qty: 13.0, cost: 30.0, unit: "ea", reorder: 3, notes: null },
    { name: "Insulated Metal Panel (AWIP)-16\'-44-4", sku: "IMP-AWIP-16-4", category: "Insulated Metal Panel", qty: 1290.67, cost: 6.5, unit: "ea", reorder: 258, notes: null },
    { name: "T-Bar Splice Plate Kit - 5\" T-Bar", sku: "CTSPL165HSKIT", category: "Trim & Accessories", qty: 39.0, cost: 12.0, unit: "ea", reorder: 8, notes: null },
    { name: "PEEL & SEAL 4\" WHITE (300LF/CTN) 9 ROLLS/CTN", sku: "TPPS04WH", category: "Miscellaneous Materials", qty: 0, cost: 161.0, unit: "ea", reorder: 0, notes: null },
    { name: "FSI VAPOR GUARD TAPE 4\" WHITE (50LF/ROLL, 9 ROLLS/CTN)", sku: "TPFSIVGT04WH", category: "Trim & Accessories", qty: 6.0, cost: 238.0, unit: "ea", reorder: 2, notes: null },
    { name: "T-Bar Accessory Kit - 5\" T-Bar", sku: "CTACCKIT165HS", category: "Trim & Accessories", qty: 18.0, cost: 10.5, unit: "ea", reorder: 4, notes: null },
    { name: "FSI VAPOR GUARD TAPE 6\" WHITE (50LF/ROLL, 6 ROLLS/CTN)", sku: "TPFSIVGT06WH", category: "Trim & Accessories", qty: 8.0, cost: 258.0, unit: "ea", reorder: 2, notes: null },
    { name: "Galvanized Sheet 4\' x 8\' (20ga)", sku: null, category: "Metal Raw Materials", qty: 12.2, cost: 60.0, unit: "ea", reorder: 2, notes: null },
    { name: "Galvanized Steel Coil - Textured White (26ga)", sku: null, category: "Metal Raw Materials", qty: 42699.0, cost: 1.44, unit: "ea", reorder: 8540, notes: null },
    { name: "34\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 7.0, cost: 54.4, unit: "ea", reorder: 2, notes: null },
    { name: "FSI VAPOR GUARD TAPE 9\" WHITE (50LF/ROLL, 4 ROLLS/CTN)", sku: "TPFSIVGT09WH", category: "Trim & Accessories", qty: 8.25, cost: 258.0, unit: "ea", reorder: 2, notes: null },
    { name: "GLUE 5635", sku: null, category: "Door Hardware/Parts", qty: 4.1, cost: 205.0, unit: "ea", reorder: 2, notes: null },
    { name: "Insulated Metal Panel (AWIP)-8\'-44-4", sku: "IMP-AWIP-8-4", category: "Insulated Metal Panel", qty: 1564.0, cost: 6.5, unit: "ea", reorder: 313, notes: null },
    { name: "ADFOAM 1825/870ML", sku: "1825", category: "Miscellaneous Materials", qty: 0, cost: 12.95, unit: "ea", reorder: 0, notes: null },
    { name: "Hook for K1094 Closer", sku: "11094000027", category: "Door Hardware/Parts", qty: 50.0, cost: 16.0, unit: "ea", reorder: 10, notes: null },
    { name: "K1248 1-1/4 OS Hinge", sku: "11248000020", category: "Door Hardware/Parts", qty: 108.0, cost: 70.2, unit: "ea", reorder: 22, notes: null },
    { name: "K1277 Cam-lift Strap Hinge", sku: "11277000012", category: "Door Hardware/Parts", qty: 82.0, cost: 59.0, unit: "ea", reorder: 16, notes: null },
    { name: "Aluminum 6\" x 6\" x 25\' Beam", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 427.8, unit: "ea", reorder: 0, notes: null },
    { name: "D276 Door Closer 1-3/8\" OS, Satin Chrome", sku: null, category: "Door Hardware/Parts", qty: 10.0, cost: 45.88, unit: "ea", reorder: 2, notes: null },
    { name: "Aluminum Angle 3\" x 5\" (.375)", sku: "AUT630506", category: "Miscellaneous Materials", qty: 0, cost: 559.0, unit: "ea", reorder: 0, notes: null },
    { name: "Diamond Plate .063 4\' x 8\'", sku: "P03.063H22DT-96-48", category: "Metal Raw Materials", qty: 2.0, cost: 133.67, unit: "ea", reorder: 2, notes: null },
    { name: "EPS Sheet 2\" x 4\' x 8\'", sku: null, category: "Miscellaneous Materials", qty: 0, cost: 18.43, unit: "ea", reorder: 0, notes: null },
    { name: "T-Bar 4\" x 16\'", sku: "CTALUPPBW164HS", category: "Trim & Accessories", qty: 14.0, cost: 177.0, unit: "ea", reorder: 3, notes: null },
    { name: "Dow 60PSI 4\' x 8\' x 3\"", sku: "12031485", category: "Miscellaneous Materials", qty: 0, cost: 80.33, unit: "ea", reorder: 0, notes: null },
    { name: "FRP .090 4\' x 10\' White", sku: "F410", category: "Trim & Accessories", qty: 3.0, cost: 70.0, unit: "ea", reorder: 2, notes: null },
    { name: "TRYMER 200L 4-1/2\" - 48\" X 96\"", sku: "118093", category: "Miscellaneous Materials", qty: 0, cost: 202.75, unit: "ea", reorder: 0, notes: null },
    { name: "46\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 4.0, cost: 73.6, unit: "ea", reorder: 2, notes: null },
    { name: "10\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Miscellaneous Materials", qty: 0, cost: 16.0, unit: "ea", reorder: 0, notes: null },
    { name: "19.5\' - HEATER, WIRE FIBERGLASS BRAID, 115V, -10DEG, SINGLE WRAP", sku: "64-200", category: "Door Hardware/Parts", qty: 9.0, cost: 29.25, unit: "ea", reorder: 2, notes: null },
    { name: "42\' - HEATER, WIRE FIBERGLASS BRAID, 115V, -10DEG, SINGLE WRAP", sku: "64-200", category: "Miscellaneous Materials", qty: 0, cost: 63.0, unit: "ea", reorder: 0, notes: null },
    { name: "Insulated Metal Panel (AWIP)-10\'-44-4", sku: "IMP-AWIP-10-4", category: "Insulated Metal Panel", qty: 2090.33, cost: 6.5, unit: "ea", reorder: 418, notes: null },
    { name: "Aluminum Angle 1.5\" x 1.5\" (.125)", sku: "AET515154", category: "Trim & Accessories", qty: 7.0, cost: 65.5, unit: "ea", reorder: 2, notes: null },
    { name: "Insulated Metal Panel (AWIP)-12\'-44-4", sku: "IMP-AWIP-12-4", category: "Insulated Metal Panel", qty: 264.0, cost: 6.5, unit: "ea", reorder: 53, notes: null },
    { name: "Insulated Metal Panel (AWIP)-14\'-44-4", sku: "IMP-AWIP-14-4", category: "Insulated Metal Panel", qty: 565.0, cost: 6.5, unit: "ea", reorder: 113, notes: null },
    { name: "Insulated Metal Panel (Falk)-20\'-40-4", sku: "IMP-FALK-20-4", category: "Insulated Metal Panel", qty: 733.0, cost: 6.5, unit: "ea", reorder: 147, notes: null },
    { name: "Insulated Metal Panel (AWIP)-11\'-44-5", sku: "IMP-AWIP-11-5", category: "Insulated Metal Panel", qty: 444.0, cost: 6.5, unit: "ea", reorder: 89, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-10\'-44-4", sku: "IMP-MS-10-4", category: "Insulated Metal Panel", qty: 807.0, cost: 6.5, unit: "ea", reorder: 161, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-12\'-44-4", sku: "IMP-MS-12-4", category: "Insulated Metal Panel", qty: 660.0, cost: 6.5, unit: "ea", reorder: 132, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-8\'-44-5", sku: "IMP-MS-8-5", category: "Insulated Metal Panel", qty: 528.0, cost: 6.5, unit: "ea", reorder: 106, notes: null },
    { name: "Threaded Rod  3/8-16x10\'", sku: "ATHRCST06C1920ZN", category: "Trim & Accessories", qty: 40.0, cost: 4.65, unit: "ea", reorder: 8, notes: null },
    { name: "Diamond Plate .125 4\' x 8\'", sku: "P03.125H22DT-96-48", category: "Metal Raw Materials", qty: 7.0, cost: 242.0, unit: "ea", reorder: 2, notes: null },
    { name: "K1245 1-3/8 OS Hinge", sku: "11245000048", category: "Door Hardware/Parts", qty: 17.0, cost: 37.11, unit: "ea", reorder: 3, notes: null },
    { name: "K1248 1-3/8 OS Hinge", sku: "11248000024", category: "Door Hardware/Parts", qty: 6.0, cost: 80.0, unit: "ea", reorder: 2, notes: null },
    { name: "K481 Safety Glow Inside Release, 6\" Door", sku: "10481A00600", category: "Door Hardware/Parts", qty: 6.0, cost: 11.5, unit: "ea", reorder: 2, notes: null },
    { name: "K486 Inside Release", sku: "10486D00400", category: "Miscellaneous Materials", qty: 0, cost: 36.5, unit: "ea", reorder: 0, notes: null },
    { name: "K489 Inside Release", sku: "10489A00600", category: "Miscellaneous Materials", qty: 0, cost: 30.4, unit: "ea", reorder: 0, notes: null },
    { name: "K481 Inside Release, Stainless Steel", sku: "10481SC0600", category: "Door Hardware/Parts", qty: 9.0, cost: 34.0, unit: "ea", reorder: 2, notes: null },
    { name: "Roller Assembly - Complete", sku: "9850000352", category: "Door Hardware/Parts", qty: 24.0, cost: 33.04, unit: "ea", reorder: 5, notes: null },
    { name: "T-Bar Splice Plate Kit - 4\" T-Bar", sku: "CTSPL164HSKIT", category: "Trim & Accessories", qty: 12.0, cost: 12.0, unit: "ea", reorder: 2, notes: null },
    { name: "T-Bar Accessory Kit - 4\" T-Bar", sku: "CTACCKIT164HS", category: "Trim & Accessories", qty: 12.0, cost: 10.5, unit: "ea", reorder: 2, notes: null },
    { name: "Metal Anchor HIT HMH 1/4\" x 1-1/4\"", sku: "66139", category: "Miscellaneous Materials", qty: 15.0, cost: 72.15, unit: "ea", reorder: 3, notes: null },
    { name: "Insulated Metal Panel (AWIP)-9\'-44-5", sku: "IMP-AWIP-9-5", category: "Insulated Metal Panel", qty: 693.0, cost: 6.5, unit: "ea", reorder: 139, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-13\'-44-4", sku: "IMP-MS-13-4", category: "Insulated Metal Panel", qty: 48.0, cost: 6.5, unit: "ea", reorder: 10, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-15\'-44-4", sku: "IMP-MS-15-4", category: "Insulated Metal Panel", qty: 55.0, cost: 6.5, unit: "ea", reorder: 11, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-20\'-44-4", sku: "IMP-MS-20-4", category: "Insulated Metal Panel", qty: 1939.0, cost: 6.5, unit: "ea", reorder: 388, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-9\'-44-5", sku: "IMP-MS-9-5", category: "Insulated Metal Panel", qty: 33.0, cost: 6.5, unit: "ea", reorder: 7, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-10\'-44-5", sku: "IMP-MS-10-5", category: "Insulated Metal Panel", qty: 293.0, cost: 6.5, unit: "ea", reorder: 59, notes: null },
    { name: "Insulated Metal Panel (MetlSpan)-12\'-44-5", sku: "IMP-MS-12-5", category: "Insulated Metal Panel", qty: 44.0, cost: 6.5, unit: "ea", reorder: 9, notes: null },
    { name: "35.67\' - HEATER, WIRE FIBERGLASS BRAID, 115V, -10DEG, SINGLE WRAP", sku: "64-200", category: "Miscellaneous Materials", qty: 0, cost: 46.8, unit: "ea", reorder: 0, notes: null },
    { name: "32\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 10.0, cost: 51.2, unit: "ea", reorder: 2, notes: null },
    { name: "44\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 3.0, cost: 70.4, unit: "ea", reorder: 2, notes: null },
    { name: "40\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 4.0, cost: 64.0, unit: "ea", reorder: 2, notes: null },
    { name: "37\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 7.0, cost: 59.2, unit: "ea", reorder: 2, notes: null },
    { name: "42\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 4.0, cost: 67.2, unit: "ea", reorder: 2, notes: null },
    { name: "47\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 4.0, cost: 75.2, unit: "ea", reorder: 2, notes: null },
    { name: "52\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Miscellaneous Materials", qty: 0, cost: 83.2, unit: "ea", reorder: 0, notes: null },
    { name: "12\' - HEATER, WIRE ALUM BRAID, 115V, -10 DEG, 2 WRAP", sku: "64-250", category: "Door Hardware/Parts", qty: 10.0, cost: 19.2, unit: "ea", reorder: 2, notes: null },
    { name: "Wiper Gasket 6.5\"", sku: null, category: "Door Hardware/Parts", qty: 5.0, cost: 170.0, unit: "ea", reorder: 2, notes: null },
    { name: "Wiper Gasket 8.5\"", sku: null, category: "Door Hardware/Parts", qty: 5.68, cost: 190.0, unit: "ea", reorder: 2, notes: null },
    { name: "Insulated Metal Panel (AWIP)-15\'-44-4", sku: "IMP-AWIP-15-4", category: "Insulated Metal Panel", qty: 110.0, cost: 6.5, unit: "ea", reorder: 22, notes: null },
    { name: "Insulated Metal Panel (AWIP)-20\'-44-4", sku: "IMP-AWIP-20-4", category: "Insulated Metal Panel", qty: 3455.67, cost: 6.5, unit: "ea", reorder: 691, notes: null },
    { name: "Insulated Metal Panel (AWIP)-10\'-44-5", sku: "IMP-AWIP-10-5", category: "Insulated Metal Panel", qty: 110.0, cost: 6.5, unit: "ea", reorder: 22, notes: null },
    { name: "15/32X48X96 ARAUCO AC RADIATA PINE Sanded (1/2\")", sku: "697055", category: "Miscellaneous Materials", qty: 0, cost: 52.0, unit: "ea", reorder: 0, notes: null },
    { name: "Adthane Glue", sku: "5635", category: "Door Hardware/Parts", qty: 9.0, cost: 260.0, unit: "ea", reorder: 2, notes: null },
    { name: "K56 Strike", sku: "10058005002", category: "Door Hardware/Parts", qty: 53.0, cost: 34.0, unit: "ea", reorder: 11, notes: null },
    { name: "D800", sku: null, category: "Door Hardware/Parts", qty: 30.0, cost: 4.15, unit: "ea", reorder: 6, notes: null },
    { name: "EPS Sheet 3.5\" x 4\' x 10\'", sku: null, category: "Foam Insulation", qty: 8.0, cost: 40.32, unit: "ea", reorder: 2, notes: null },
    { name: "Galvanized Angle (16ga) 3\" x 6\" x 10\'", sku: null, category: "Trim & Accessories", qty: 7.0, cost: 28.58, unit: "ea", reorder: 2, notes: null },
    { name: "Galvanized Screed 16ga 2\" x 4.25\" x 1.5\"", sku: null, category: "Trim & Accessories", qty: 69.0, cost: 25.9, unit: "ea", reorder: 14, notes: null },
    { name: "TWS Cap 2\" x 4.25\" x 2\"", sku: null, category: "Trim & Accessories", qty: 18.0, cost: 1.66, unit: "ea", reorder: 4, notes: null },
    { name: "Galvanized Steel Coil - Smooth White (26ga)", sku: null, category: "Metal Raw Materials", qty: 9704.0, cost: 1.1, unit: "ea", reorder: 1941, notes: null },
    { name: "Galvanized Sheet 4\' x 8\' (16ga)", sku: null, category: "Metal Raw Materials", qty: 3.0, cost: 55.0, unit: "ea", reorder: 2, notes: null },
    { name: "Galvanized Sheet Flatstock - Smooth White - Igloo White 4\' x 8\' (26ga)", sku: null, category: "Metal Raw Materials", qty: 42.0, cost: 118.88, unit: "ea", reorder: 8, notes: null },
    { name: "Galvanized Sheet Flatstock - Textured White - Igloo White 4\' x 8\' (26ga)", sku: null, category: "Metal Raw Materials", qty: 48.0, cost: 118.88, unit: "ea", reorder: 10, notes: null },
    { name: "19/32X48X96 ARAUCO AC RADIATA PINE Sanded (5/8\")", sku: "697056", category: "Miscellaneous Materials", qty: 106.0, cost: 40.29, unit: "ea", reorder: 21, notes: null },
    { name: "FROTH-PAK 200", sku: null, category: "Foam Insulation", qty: 22.0, cost: 365.0, unit: "ea", reorder: 4, notes: null },
    { name: "Kason 48\" Slider Trolley (Right)", sku: "98600003400480R", category: "Door Hardware/Parts", qty: 2.0, cost: 540.0, unit: "ea", reorder: 2, notes: null },
    { name: "Kason 72\" Slider Trolley (Right)", sku: "98600003400720R", category: "Door Hardware/Parts", qty: 1.0, cost: 745.83, unit: "ea", reorder: 2, notes: null },
    { name: "Kason 96\" Slider Trolley (Right)", sku: "98600003400960R", category: "Door Hardware/Parts", qty: 2.0, cost: 769.78, unit: "ea", reorder: 2, notes: null },
    { name: "FSI-96 BUTYL", sku: "CAFSI96PT10WH", category: "Trim & Accessories", qty: 1422.0, cost: 4.1, unit: "ea", reorder: 284, notes: null },
    { name: "SSSH 0408 24 - Unpolished", sku: null, category: "Metal Raw Materials", qty: 3.0, cost: 183.5, unit: "ea", reorder: 2, notes: null },
    { name: "SSSH 0408 16", sku: null, category: "Metal Raw Materials", qty: 2.0, cost: 471.81, unit: "ea", reorder: 2, notes: null },
    { name: "Replacement Strip Curtains 8\" x .080 - 50% overlap (96\" x 96\")", sku: "Repl Strips", category: "Doors (by others)", qty: 2.0, cost: 373.83, unit: "ea", reorder: 2, notes: null },
    { name: "T-Bar 5\" x 16\'", sku: "CTALUPPBW165HS", category: "Trim & Accessories", qty: 39.0, cost: 225.0, unit: "ea", reorder: 8, notes: null },
    { name: "Clear Plastic Film SGPQA87C 48\" x 1000\' ROLL", sku: "SGPQA87C", category: "Miscellaneous Materials", qty: 1.0, cost: 504.0, unit: "ea", reorder: 2, notes: null },
  ]

  let created = 0
  let skipped = 0
  for (const p of products) {
    const categoryId = catMap.get(p.category)
    if (!categoryId) {
      console.warn(`Skipping ${p.name}: no category "${p.category}"`)
      skipped++
      continue
    }

    try {
      await prisma.product.create({
        data: {
          name: p.name,
          sku: p.sku,
          categoryId,
          unitOfMeasure: p.unit,
          currentQty: p.qty,
          avgCost: p.cost,
          lastCost: p.cost,
          reorderPoint: p.reorder,
          notes: p.notes,
        },
      })
      created++
    } catch (e) {
      // Skip duplicates (same SKU)
      skipped++
    }
  }

  console.log(`Created ${created} products (${skipped} skipped)`)
  console.log("Seed complete!")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
